// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3FYnvpTA72-1z3KHFAlm10H6HVkGTmCQ',
    appId: '1:209729532551:web:7d614c6c81eba9b82e3e22',
    messagingSenderId: '209729532551',
    projectId: 'udemy-new-sns-app',
    authDomain: 'udemy-new-sns-app.firebaseapp.com',
    storageBucket: 'udemy-new-sns-app.appspot.com',
    measurementId: 'G-RKB80Q484R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaGkW89BlDjaDIOVFANxAd20Gdp5DEQDs',
    appId: '1:209729532551:android:f96cd0c42a82bdab2e3e22',
    messagingSenderId: '209729532551',
    projectId: 'udemy-new-sns-app',
    storageBucket: 'udemy-new-sns-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQch9ZYuNCqEOFnetr82JDbDNaQiv2diE',
    appId: '1:209729532551:ios:8f9a991c04d07af62e3e22',
    messagingSenderId: '209729532551',
    projectId: 'udemy-new-sns-app',
    storageBucket: 'udemy-new-sns-app.appspot.com',
    iosBundleId: 'com.example.udemyFlutterSns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQch9ZYuNCqEOFnetr82JDbDNaQiv2diE',
    appId: '1:209729532551:ios:8f9a991c04d07af62e3e22',
    messagingSenderId: '209729532551',
    projectId: 'udemy-new-sns-app',
    storageBucket: 'udemy-new-sns-app.appspot.com',
    iosBundleId: 'com.example.udemyFlutterSns',
  );
}
